apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: adaptation-service
        image: glasswallsolutions/icap-adaptation-service
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMQP_URL
          value: {{ .Values.deployment.amqpurl }}
        - name: INPUT_MOUNT
          value: {{ .Values.deployment.inputmount }}
        - name: OUTPUT_MOUNT
          value: {{ .Values.deployment.outputmount }}
          - name: POD_IMAGE
          value: {{ .Values.deployment.image }}          
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 0.5
            memory: 100Mi