environment:
serviceAccount:
  name: adaptation-service-sa
deployment:
  name: adaptation-service
  namespace: icap-adaptation
  image: peltops/icap-request-processing:v0.1
  replicas: 1
  amqpurl: "amqp://guest:guest@rabbitmq-service:5672/"
  inputmount: "/var/source"
  outputmount: "/var/target"
volumes:
  sourcepath: "/run/desktop/mnt/host/c/test-data"
  targetpath: "/run/desktop/mnt/host/c/test-data-output"